
spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.108.67:3306/xuebaofile?useUnicode=true&characterEncoding=utf8
    username: root
    password: sunwang1
  redis:
    database: 0
    host: 47.107.108.67
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
    timeout: 5s

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  thymeleaf:
#    prefix: /templates/
#    suffix: .html
server:
  port: 8081
#    encoding: UTF-8